<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2015/09/13 16:09:25
return array(

  // sfPropelORMPlugin_module_libs

  // sfTCPDFPlugin_module_libs
  'sfTCPDF/basesftcpdfactions' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/modules/sfTCPDF/lib/BasesfTCPDFActions.class.php',

  // sfTCPDFPlugin_lib
  'sftcpdfpluginconfighandler' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/config/sfTCPDFPluginConfigHandler.class.php',
  'sftcpdf' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/sfTCPDF.class.php',
  'tcpdf2dbarcode' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/2dbarcodes.php',
  'tcpdfbarcode' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/barcodes.php',
  'datamatrix' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/datamatrix.php',
  'tcpdf_encoding_maps' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/encodings_maps.php',
  'mypdf' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/examples/example_051.php',
  'mc_tcpdf' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/examples/example_010.php',
  'toc_tcpdf' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/examples/example_059.php',
  'pdf417' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/pdf417.php',
  'qrcode' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/qrcode.php',
  'tcpdf' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/tcpdf.php',
  'tcpdf_filters' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/tcpdf_filters.php',
  'tcpdf_parser' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/tcpdf_parser.php',
  'tcpdf_unicode_data' => 'C:/wamp/www/estadistica/plugins/sfTCPDFPlugin/lib/tcpdf/unicode_data.php',

  // sfJqueryReloadedPlugin_module_libs

  // sfJqueryReloadedPlugin_lib

  // sfJQueryUIPlugin_module_libs

  // sfJQueryUIPlugin_lib
  'sfwidgetformdatejqueryui' => 'C:/wamp/www/estadistica/plugins/sfJQueryUIPlugin/lib/widget/sfWidgetFormDateJQueryUI.class.php',

  // sfFormExtraPlugin_module_libs

  // sfFormExtraPlugin_lib
  'sfformlanguage' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/form/sfFormLanguage.class.php',
  'sfvalidatordoctrinenestedsetlevel' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/validator/doctrine/sfValidatorDoctrineNestedSetLevel.class.php',
  'sfvalidatorblacklist' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/validator/sfValidatorBlacklist.class.php',
  'sfvalidatordefault' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/validator/sfValidatorDefault.class.php',
  'sfvalidatorrecaptcha' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/validator/sfValidatorReCaptcha.class.php',
  'sfvalidatorschematimeinterval' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/validator/sfValidatorSchemaTimeInterval.class.php',
  'sfwidgetformdoctrinechoicegrouped' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormDoctrineChoiceGrouped.class.php',
  'sfwidgetformdoctrinejqueryautocompleter' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormDoctrineJQueryAutocompleter.class.php',
  'sfwidgetformjqueryautocompleter' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormJQueryAutocompleter.class.php',
  'sfwidgetformjquerydate' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormJQueryDate.class.php',
  'sfwidgetformpropelchoicegrouped' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormPropelChoiceGrouped.class.php',
  'sfwidgetformpropeljqueryautocompleter' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormPropelJQueryAutocompleter.class.php',
  'sfwidgetformrecaptcha' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormReCaptcha.class.php',
  'sfwidgetformselectdoublelist' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormSelectDoubleList.class.php',
  'sfwidgetformselectusstate' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormSelectUSState.class.php',
  'sfwidgetformtextareatinymce' => 'C:/wamp/www/estadistica/plugins/sfFormExtraPlugin/lib/widget/sfWidgetFormTextareaTinyMCE.class.php',

  // sfPropelORMPlugin_lib
  'sfmixer' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropeldata' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropelData.class.php',
  'sfpropeldatabaseschema' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfpropelmanytomany' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropelbehaviorbase' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18n' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviori18ntranslation' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviorsymfony' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviortimestampable' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatabase' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/database/sfPropelDatabase.class.php',
  'sfwebdebugpanelpropel' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfformfilterpropel' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/form/sfFormPropel.class.php',
  'sfformpropelcollection' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/form/sfFormPropelCollection.class.php',
  'sfpropelformfiltergenerator' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropellogger' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/log/sfPropelLogger.class.php',
  'swift_propelspool' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelormroute' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/routing/sfPropelORMRoute.class.php',
  'sfpropelormroutecollection' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/routing/sfPropelORMRouteCollection.class.php',
  'sfpropelroute' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfphing' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPhing.class.php',
  'sfphinglistener' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPhingListener.php',
  'sfpropelbasetask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildalltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelbuildfilterstask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildformstask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelbuildmodeltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfpropelbuildschematask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelbuildsqltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropelconfiguredatabasetask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropeldatadumptask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropeldataloadtask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropeldifftask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelDiffTask.class.php',
  'sfpropelgenerateadmintask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgeneratemoduletask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgraphviztask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelinsertsqltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelmigratedowntask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelMigrateDownTask.class.php',
  'sfpropelmigratetask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelMigrateTask.class.php',
  'sfpropelmigrateuptask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelMigrateUpTask.class.php',
  'sfpropelschematoxmltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelschematoymltask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropelstatustask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelStatusTask.class.php',
  'sfpropelversiontask' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/task/sfPropelVersionTask.class.php',
  'sftesterpropel' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/test/sfTesterPropel.class.php',
  'sfvalidatorpropelchoice' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfvalidatorschemaremove' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/validator/sfValidatorSchemaRemove.php',
  'sfwidgetformdelete' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/widget/sfWidgetFormDelete.class.php',
  'sfwidgetformplain' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/widget/sfWidgetFormPlain.php',
  'sfwidgetformpropelchoice' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfwidgetformschemadecoratorescaped' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/widget/sfWidgetFormSchemaDecoratorEscaped.class.php',
  'sfwidgetformschemaoptional' => 'C:/wamp/www/estadistica/plugins/sfPropelORMPlugin/lib/widget/sfWidgetFormSchemaOptional.class.php',

  // project
  'baseusuarioformfilter' => 'C:/wamp/www/estadistica/lib/filter/base/BaseUsuarioFormFilter.class.php',
  'baseformfilterpropel' => 'C:/wamp/www/estadistica/lib/filter/BaseFormFilterPropel.class.php',
  'usuarioformfilter' => 'C:/wamp/www/estadistica/lib/filter/UsuarioFormFilter.class.php',
  'baseusuarioform' => 'C:/wamp/www/estadistica/lib/form/base/BaseUsuarioForm.class.php',
  'baseform' => 'C:/wamp/www/estadistica/lib/form/BaseForm.class.php',
  'baseformpropel' => 'C:/wamp/www/estadistica/lib/form/BaseFormPropel.class.php',
  'loginportalform' => 'C:/wamp/www/estadistica/lib/form/LoginPortalForm.class.php',
  'usuarioform' => 'C:/wamp/www/estadistica/lib/form/UsuarioForm.class.php',

  // project_model
  'usuariotablemap' => 'C:/wamp/www/estadistica/lib/model/map/UsuarioTableMap.php',
  'baseusuario' => 'C:/wamp/www/estadistica/lib/model/om/BaseUsuario.php',
  'baseusuariopeer' => 'C:/wamp/www/estadistica/lib/model/om/BaseUsuarioPeer.php',
  'baseusuarioquery' => 'C:/wamp/www/estadistica/lib/model/om/BaseUsuarioQuery.php',
  'usuario' => 'C:/wamp/www/estadistica/lib/model/Usuario.php',
  'usuariopeer' => 'C:/wamp/www/estadistica/lib/model/UsuarioPeer.php',
  'usuarioquery' => 'C:/wamp/www/estadistica/lib/model/UsuarioQuery.php',

  // application
  'myuser' => 'C:/wamp/www/estadistica/apps/estadistica/lib/myUser.class.php',

  // modules
);
