<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/09/13 16:09:26
$this->security = array (
  'login' => 
  array (
    'is_secure' => 'false;',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
